// Import mongoose and Schema
const mongoose = require('mongoose');
const Schema = mongoose.Schema;

// Define the session schema
const sessionSchema = new Schema({
  // Reference the user model by user._id
  user: {
    type: Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  // Store the sessionID generated by express-session
  sessionID: {
    type: String,
    required: true,
  },
  // Store the date and time of creation
  createdAt: {
    type: Date,
    default: Date.now,
  },
});

// Export the session model
module.exports = mongoose.model('Session', sessionSchema);
